version: '3.8'

services:
  tverrec:
    container_name: bulkdownload
    image: dongaba/tverrec:latest
    hostname: 'tverrec'
    restart: always
    tty: true

    #network_mode: "host"
    #pid: "host"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "20022:20022"
    build:
      context: .
      dockerfile: ./Dockerfile

    environment:
      POWERSHELL_TELEMETRY_OPTOUT: 1
      COMPOSE_PROJECT_NAME: tverrec

    tmpfs:
      - /mnt/Temp
    volumes:
      - type: bind
        source: /mnt/c/Work
        target: /mnt/Work
      - type: bind
        source: /mnt/c/Video
        target: /mnt/Video
      - type: bind
        source: /TVerRec/conf
        target: /app/TVerRec/conf
      - type: bind
        source: /TVerRec/db
        target: /app/TVerRec/db
      - type: bind
        source: /TVerRec/list
        target: /app/TVerRec/list

    cap_add:
      - NET_ADMIN
    cap_drop:
      - SYS_ADMIN

