version: '3.8'

services:
  tverrec:
    container_name: bulkdownload
    image: dongaba/tverrec:latest
    hostname: 'tverrec'
    restart: unless-stopped
    tty: true
    user: tverrec

    #network_mode: "host"
    build:
      context: .
      dockerfile: ./Dockerfile

    environment:
      POWERSHELL_TELEMETRY_OPTOUT: 1
      COMPOSE_PROJECT_NAME: tverrec

    tmpfs:
      - /mnt/Temp
    volumes:
      - type: bind
        source: /mnt/c/Work
        target: /mnt/Work
      - type: bind
        source: /mnt/c/Video
        target: /mnt/Video
      - type: bind
        source: /TVerRec/conf
        target: /app/TVerRec/conf
      - type: bind
        source: /TVerRec/db
        target: /app/TVerRec/db
      - type: bind
        source: /TVerRec/list
        target: /app/TVerRec/list

    cap_add:
      - ALL

    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
