version: '3.8'

services:
  tverrec:
    container_name: bulkdownload
    image: dongaba/tverrec:latest
    hostname: 'tverrec'
    restart: unless-stopped
    user: tverrec
    network_mode: "host"

    build:
      context: .
      dockerfile: ./Dockerfile

    environment:
      POWERSHELL_TELEMETRY_OPTOUT: 1
      COMPOSE_PROJECT_NAME: tverrec

    tmpfs:
      - /mnt/Temp
    volumes:
      - type: bind
        source: ~/ContainerData/Work
        target: /mnt/Work
      - type: bind
        source: ~/ContainerData/Video
        target: /mnt/Video
      - type: bind
        source: ~/ContainerData/conf/user_setting.ps1
        target: /app/TVerRec/conf/user_setting.ps1
      - type: bind
        source: ~/ContainerData/db
        target: /app/TVerRec/db
      - type: bind
        source: ~/ContainerData/list
        target: /app/TVerRec/list

    cap_add:
      - ALL

    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
