version: "3.8"

services:
  tverrec:
    container_name: TVerRec-loop
    image: dongaba/tverrec:latest
    hostname: "tverrec"
    restart: unless-stopped
    tty: true
    stdin_open: true

    build:
      context: .
      dockerfile: ./Dockerfile

    environment:
      POWERSHELL_TELEMETRY_OPTOUT: 1

    tmpfs:
      - /mnt/Temp

    volumes:
      - temp:/mnt/Temp
      - work:/mnt/Work
      - save:/mnt/Save
      - container-data:/app/TVerRec/container-data

volumes:
  temp:
  work:
  save:
  container-data:
