name: PSScriptAnalyzer

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "32 20 * * 4"

permissions:
  contents: read

jobs:
  psscriptanalyzer-security-scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.0
        with:
          path: .\src
          #customRulePath: '".\customRule.ps1", "customRule2.ps1"'
          #recurseCustomRulePath: false
          #excludeRule: "PSAlignAssignmentStatement"'
          includeDefaultRules: true
          #includeRule: '"PSAvoidGlobalAliases", "PSAvoidUsingConvertToSecureStringWithPlainText"'
          severity: '"Error", "Warning"'
          recurse: true
          #suppressedOnly: false
          #fix: false
          #enableExit: true
          settings: .\.vscode\analyzersettings.psd1
          output: results.sarif
          #ignorePattern: 'tests'

      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
