name: Build and Push image to Docker Hub

on:
  push:
    branches: [master, dev]
    tags:
      - "v*.*.*"

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push_to_dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # タグ名の設定
      - name: Set Tag Name as Preparation
        id: prep
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/dev ]]; then
            TAG="dev"
          else
            TAG="latest"
          fi
          echo "tag=${IMAGE_NAME}:${TAG}" >> $GITHUB_ENV

      # リポジトリのチェックアウト
      - name: Check out the repo
        uses: actions/checkout@v4

      # Dockerのメタデータ収集
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      # QEMUのセットアップ
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Docker Buildxのセットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 利用可能なプラットフォームの確認
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      # Docker Hubへのログイン
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # ビルドとプッシュ
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./resources/docker
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.TAG }}
          labels: ${{ steps.meta.outputs.labels }}

      # Docker HubにREADME.mdをプッシュ
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.IMAGE_NAME }}
          readme-filepath: ./README.md
