name: Build and Push image to GitHub Conainer Registry

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: dongaba/tverrec

jobs:
  push_to_ghcr:
    name: Push Docker image to GitHub Container Repository
    runs-on: ubuntu-latest
    steps:

      #Check out
      - name: Check out the repo
        uses: actions/checkout@v3

      #Collect metadata
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          #images: ghcr.io/dongaba/tverrec
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      #Build Preperation
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      #Confirm available platforms
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      #Login to GitHub Container Registry
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_FOR_GHCR }}

      #Build & Push
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          push: true
          tags: ghcr.io/${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
